import { useEffect, useMemo, useState } from "react";
import { useShortcuts } from "../hooks/useKeyboard";
import { useClients } from "../hooks/useClients";
import { useTriageDeadlines } from "../hooks/useDeadlines";
import { useDetectAnnouncements } from "../hooks/useAnnouncements";
import { useRealtimeAnnouncements } from "../hooks/useRealtimeAnnouncements";
import { useStore } from "../data/store";
import { useSession } from "../data/session";
import { ShortcutsModal } from "../components/ShortcutsModal";
import { DashboardSkeleton } from "../components/skeletons/DashboardSkeleton";
import { ErrorState } from "../components/ErrorState";
import {
  TODAY,
  toIso,
  daysBetween,
  parseDate,
  hoursSince,
  escalationTier,
} from "../data/dateHelpers";
import { useDashboardPreferences } from "../data/preferences";
import { ChaseBanner } from "../components/ChaseBanner";
import { BlockingAlertsDialog } from "../components/BlockingAlertsDialog";
import { OnboardingLayer2Widget } from "../components/OnboardingLayer2Widget";
// import { WelcomeTour } from "../components/WelcomeTour"; // hidden per user direction
import { CapacityStrip } from "../components/CapacityStrip";
// ModeFHealth removed — the same monitoring signal ("50/50 states ·
// last scrape 14m ago") is already on /alerts as the ambient line.
// Two surfaces showing the same health was redundant.
// import { ModeFHealth } from "../components/ModeFHealth";
import { ActionQueue } from "../components/ActionQueue";
import { MorningTriage } from "../components/MorningTriage";
import { AlertTriageModal } from "../components/AlertTriageModal";
import { trpc } from "../lib/api/client";
import { AiUsageInfo } from "../components/AiUsageInfo";
import { PageHeader } from "../components/ui/PageHeader";
import { DateLabel } from "../components/ui/DateLabel";
import { SectionHeader } from "../components/ui/SectionHeader";
import { Megaphone, ChevronRight } from "lucide-react";
import { Link, useLocation, useNavigate } from "react-router-dom";
import type { Announcement } from "../types";
import { escalationTier as escTier } from "../data/dateHelpers";

const DONE_STATUSES = new Set(["completed", "filed_extension"]);

/**
 * Dashboard — the morning glance.
 *
 * Two zones above the fold:
 *   1. State-alert band — conditional, vanishes when no actionable alerts
 *   2. The queue — ActionQueue (urgency-sorted, with chase actions inline)
 *
 * Below the fold: capacity strip (≥3-staff firms only).
 *
 * Editorial rules:
 *   • CPAs barely miss official deadlines — so "past official" is rare and
 *     gets a calm-but-clear callout only when nonzero. The operational
 *     signal is "past internal target" (the firm's 1-week buffer is being
 *     eaten), which fires regularly during tax season.
 *   • No big greeting cards or hero stat strips. A thin top strip with the
 *     date and a one-line summary; the queue starts immediately below.
 *   • Welcome tour, PWA install, advisory peek, digest panel are NOT on
 *     this surface (they were noise — moved to Settings, /to-review, or
 *     surfaced via per-row actions in the queue).
 */
export function Dashboard() {
  useSession();
  const clientsQuery = useClients();
  const triageQuery = useTriageDeadlines();
  const announcementsQuery = useRealtimeAnnouncements();
  const detectMutation = useDetectAnnouncements();
  const { tasks } = useStore();
  const location = useLocation();
  // /legacy/dashboard renders the pre-v0.7-amendment view: deadline list only,
  // no ActionQueue, no state-monitor Health. Lets us A/B compare during transition.
  const isLegacy = location.pathname.startsWith("/legacy");

  // One-shot: run the detector on mount (simulates 24h SLA scrape)
  useEffect(() => {
    detectMutation.mutate();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const { prefs, update } = useDashboardPreferences();

  const [shortcutsOpen, setShortcutsOpen] = useState(false);

  useShortcuts([
    { key: "j", description: "Next row", handler: () => focusAdjacentRow(1) },
    { key: "k", description: "Previous row", handler: () => focusAdjacentRow(-1) },
    {
      key: "?",
      shift: true,
      description: "Show shortcuts",
      handler: () => setShortcutsOpen(true),
    },
  ]);

  const clients = clientsQuery.data?.items ?? [];
  const announcements = announcementsQuery.data ?? [];

  // Two surfaces work together (per Yuqi's "[State notification + suggested
  // actions = THE surface]" — the alert is the news; the queue carries the
  // derived verbs):
  //   • AnnouncementBanner ("State alerts") — receives EVERY undismissed
  //     alert. Renders actionable ones as full rows and folds news-only
  //     alerts into a "N news items" chip. This is the single canonical
  //     surface for the alerts themselves.
  //   • ActionQueue — receives state-alert TodoItems generated by state-monitor
  //     (separately persisted on the BE). Surfaces the *actions* a CPA
  //     should take in response ("Review draft for 6 clients", etc.).
  //   The previous one-surface approach (PR #44 — alerts moved into queue,
  //   banner was news-only) failed when state-monitor hadn't generated a
  //   corresponding TodoItem yet: alerts vanished from both surfaces and
  //   the user only saw "5 active alerts" in the StateMonitoringHealth
  //   strip with no way to act on them. Belt-and-suspenders: the banner
  //   always shows the alerts; the queue is a derived view, not the only
  //   path.
  const activeBanners = announcements.filter((a) => !a.dismissed);
  // firmRelevantAlerts (alerts hitting at least one client) still drives
  // the >72h blocking dialog — that escalation only makes sense when a
  // client cares about the alert.
  const firmRelevantAlerts = activeBanners.filter(
    (a) => a.affectedClientIds.length > 0,
  );

  const alertsByTier = useMemo(() => {
    const out = {
      fresh: [] as Announcement[],
      reminder: [] as Announcement[],
      escalated: [] as Announcement[],
      blocking: [] as Announcement[],
    };
    for (const a of firmRelevantAlerts) {
      out[escalationTier(hoursSince(a.detectedAt))].push(a);
    }
    return out;
  }, [firmRelevantAlerts]);

  // In mock/demo mode TODAY is a fixed constant (2026-04-23), so a single
  // "Snooze for today" click would otherwise lock the modal off forever.
  // Bypass the gate in mock mode so every fresh landing re-raises it.
  const isMockMode = import.meta.env.VITE_USE_MOCK_DATA !== "false";
  const alertsSnoozedToday =
    !isMockMode && prefs.alerts_snoozed_until === toIso(TODAY);
  const showBlockingDialog =
    alertsByTier.blocking.length > 0 && !alertsSnoozedToday;
  const [blockingDismissed, setBlockingDismissed] = useState(false);

  // Operational summary. Two distinct signals:
  //   • pastInternalTarget — task is past its internal target date (1-week
  //     buffer eaten). Daily-relevant. The signal Sarah actually feels.
  //   • pastOfficial — task is past the government deadline. Rare. Means
  //     extension territory. Almost always 0 in a healthy firm.
  // Plus: dueThisWeek — calendar context. Always shown.
  const summary = useMemo(() => {
    const open = tasks.filter((t) => !DONE_STATUSES.has(t.status));
    const todayIso = toIso(TODAY);
    const pastInternalTarget = open.filter(
      (t) => t.internalTargetDate < todayIso && t.officialDueDate >= todayIso,
    ).length;
    const pastOfficial = open.filter(
      (t) => t.officialDueDate < todayIso,
    ).length;
    const dueToday = open.filter((t) => t.officialDueDate === todayIso).length;
    const dueThisWeek = open.filter((t) => {
      const days = daysBetween(TODAY, parseDate(t.officialDueDate));
      return days >= 0 && days <= 7;
    }).length;
    const activeClients = clients.filter((c) => c.status === "active").length;
    return {
      pastInternalTarget,
      pastOfficial,
      dueToday,
      dueThisWeek,
      activeClients,
    };
  }, [tasks, clients]);

  const todayIso = useMemo(() => toIso(TODAY), []);

  const hasNoClients = clients.length === 0;

  const isLoading = clientsQuery.isLoading || triageQuery.isLoading;
  const loadError =
    clientsQuery.error || triageQuery.error || announcementsQuery.error;

  if (isLoading) return <DashboardSkeleton />;

  if (loadError) {
    return (
      <div className="max-w-5xl mx-auto px-4 md:px-6 py-6">
        <ErrorState
          title="Couldn't load your dashboard."
          message={loadError instanceof Error ? loadError.message : undefined}
          onRetry={() => {
            clientsQuery.refetch();
            triageQuery.refetch();
            announcementsQuery.refetch();
          }}
        />
      </div>
    );
  }

  if (hasNoClients) {
    return (
      <div className="max-w-[840px] mx-auto px-4 md:px-6 lg:px-8 py-section">
        <PageHeader
          title={
            <>
              Today
              <span className="ml-2 font-medium text-ink-500">
                <DateLabel value={todayIso} format="short" />
              </span>
            </>
          }
        />
        <EmptyState
          title="Let's get your clients in."
          actions={
            <>
              <EmptyStateButton to="/import" primary>
                Import CSV
              </EmptyStateButton>
              <EmptyStateButton to="/clients">Add 5 manually</EmptyStateButton>
              <EmptyStateButton to="/import?demo=1">
                Try demo data
              </EmptyStateButton>
            </>
          }
        />
      </div>
    );
  }

  return (
    <div className="max-w-[1080px] mx-auto px-4 md:px-6 lg:px-8 py-6 md:py-8">
      {/* Triage modal — fires once per browser session on first land
          when the user has alerts that arrived while they were away.
          Honors the per-user toggle in Settings → Notifications. */}
      <AlertTriageModal />

      {/* PAGE HEADER ROW — Mercury Home anatomy: H1 left + action button row
          right. The action row carries the page's "what can I do here right
          now" affordances (Mercury Home: Send / Transfer / Deposit / Request).
          Per T2 — only the first action ("Send chase") wears the indigo
          accent; the rest are ghost pills. */}
      <div className="mb-region flex items-end justify-between gap-region flex-wrap">
        <PageHeader
          className="mb-0"
          title={
            <>
              Today
              <span className="ml-2 font-medium text-ink-500">
                <DateLabel value={todayIso} format="short" />
              </span>
            </>
          }
        />
      </div>

      {/* §1: Morning triage — calendar-truth status strip.
          A single thin row summarizing past official / due today /
          behind plan counts. The previous design (three banner-weight
          tinted cards) competed visually with the white "Alerts to act
          on today" container directly below — same shape, two voices.
          Strip-shape sidesteps the collision and saves ~150px. The
          per-item next-gestures (anomalies, replies, inbound to
          confirm) live in the action queue's TodoItem feed below. */}
      <MorningTriage summary={summary} />

      {/* State alerts — preview surface. Top 3 escalated rows with a
          freshness chip ("N new since last visit") in the section meta
          when applicable; this absorbs what the old WhatChangedBanner
          did, eliminating the duplicate "5 new state alerts" amber
          callout that used to sit above the same list. */}
      <StateAlertsPreview announcements={activeBanners} />

      {/* §2: Action queue — AI-curated TodoItem feed (PRD §4.8 nine
          sources, urgency-sorted with waiting_multiplier). State alerts
          pinned at the top of the queue (state-monitor rows render with a
          distinct event-shape variant); per-client rows aggregate every
          outstanding item for that client into a single send. Old per-
          (client × task × form × state) row layout was theatrical at
          scale (49 clients × 6 forms = 294 rows). */}
      {!isLegacy && <ActionQueue />}

      {/* §3: Quiet clients — automation has run out. The phone-call
          subset of in-flight chases (14d+ since last reminder, still
          waiting). Self-vanishes when zero. */}
      <ChaseBanner />

      {/* §4: ModeFHealth removed — see import block above. The state-
          monitoring health signal lives once, on the /alerts page
          ambient line ("50/50 states monitored · last scrape 14m ago"),
          which the Dashboard's StateAlertsPreview links into. */}

      {/* §5: Capacity — ≥3-staff firms only (gate inside the component).
          Solo Sarah never sees this; mid-firm Yan Jing always does. */}
      <CapacityStrip />

      {/* Onboarding layer-2 nudges (set up forwarding email, connect
          QBO). Self-gated to fade out once the firm wires the basics. */}
      <OnboardingLayer2Widget />

      {/* Blocking-alerts overlay — fires only at >72h escalation. Stays as
          a modal because the spec demands a forced ack at that tier. */}
      {showBlockingDialog && !blockingDismissed && (
        <BlockingAlertsDialog
          alerts={alertsByTier.blocking}
          onSnooze={(reason) => {
            update({ alerts_snoozed_until: toIso(TODAY) });
            if (reason) {
              console.info("[alerts] snooze logged", {
                date: toIso(TODAY),
                reason,
              });
            }
            setBlockingDismissed(true);
          }}
          onClose={() => setBlockingDismissed(true)}
        />
      )}

      <ShortcutsModal
        open={shortcutsOpen}
        onClose={() => setShortcutsOpen(false)}
        shortcuts={[
          { keys: ["j"], label: "Next deadline row" },
          { keys: ["k"], label: "Previous deadline row" },
          { keys: ["Enter"], label: "Open focused row's actions" },
          { keys: ["c"], label: "Mark focused row complete" },
          { keys: ["/"], label: "Focus filter" },
          { keys: ["⌘", "k"], label: "Open search" },
          { keys: ["?"], label: "Show this help" },
          { keys: ["Esc"], label: "Close dialog" },
        ]}
      />

      <div className="pt-2 pb-6 text-2xs text-ink-400 flex items-center justify-between gap-4">
        <AiUsageInfo />
        <button
          onClick={() => setShortcutsOpen(true)}
          className="hover:text-ink-700 flex items-center gap-1"
        >
          <kbd className="px-1 py-0.5 border border-line rounded font-mono">
            ?
          </kbd>
          for shortcuts
        </button>
      </div>
    </div>
  );
}

// StateAlertsPreview — Dashboard's compact alert surface.
//
// Hard rule: Dashboard shows ONLY escalated alerts (>72h unactioned —
// past soft SLA, demand action TODAY). Routine alerts collapse to an
// ambient count line — they're one sidebar click away on /alerts.
//
// This earns the section's real estate. Routine alerts on Today
// duplicated the /alerts page for no UX gain; the CPA is going to
// /alerts to act on them anyway. Reserving Today for the truly
// urgent makes the morning glance honest.
//
// Freshness signal — "N new since last visit" — is rendered as a chip
// in the SectionHeader meta whenever `triageOnFirstLand` returns rows.
// This used to be a separate `<WhatChangedBanner>` above this section,
// but that was a duplicate amber callout for the same announcements
// already listed below. One section, one signal.
//
// Four states:
//   • 0 alerts                 → calm "all clear" line
//   • 0 escalated, 0 new       → ambient line ("N affecting · all under SLA")
//   • 0 escalated, M new       → list M new since-last-visit alerts
//   • E escalated, M new       → list E + freshness chip in header meta
function StateAlertsPreview({
  announcements,
}: {
  announcements: Announcement[];
}) {
  const navigate = useNavigate();
  const triageQuery = trpc.announcements.triageOnFirstLand.useQuery(undefined, {
    staleTime: 30_000,
    refetchOnWindowFocus: false,
  });
  const newSinceLastVisit = triageQuery.data ?? [];

  // Empty: monitoring assurance, calm.
  if (announcements.length === 0) {
    return (
      <section
        className="bg-surface border border-line rounded-md px-4 py-2.5 flex items-center gap-3 mb-section"
        aria-label="State alerts"
      >
        <span
          className="w-2 h-2 rounded-full shrink-0 bg-ok-solid"
          aria-hidden
        />
        <Megaphone className="w-3.5 h-3.5 shrink-0 text-ink-500" aria-hidden />
        <span className="flex-1 text-sm text-ink-700">
          <span className="font-medium text-ink-900">All clear.</span>{" "}
          <span className="text-ink-500">
            Monitoring 50 state authorities — nothing affecting your clients
            right now.
          </span>
        </span>
        <Link
          to="/alerts"
          className="text-2xs text-ink-500 hover:text-ink-900 inline-flex items-center gap-0.5 shrink-0"
        >
          History <ChevronRight className="w-3 h-3" aria-hidden />
        </Link>
      </section>
    );
  }

  // Affecting-firm subset.
  const affecting = announcements.filter(
    (a) => !a.dismissed && a.affectedClientIds.length > 0,
  );

  // Escalated subset — the only thing that earns Today's real estate.
  const escalated = affecting.filter(
    (a) => escTier(hoursSince(a.detectedAt)) === "escalated",
  );
  const routineCount = affecting.length - escalated.length;

  // No escalated — but if there are new-since-last-visit alerts, surface
  // those instead of collapsing to the ambient line. The user shouldn't
  // miss "5 new state alerts" just because none of them are past 72h SLA.
  if (escalated.length === 0) {
    if (newSinceLastVisit.length > 0) {
      const newIds = new Set(newSinceLastVisit.map((n) => n.id));
      const newAlerts = affecting.filter((a) => newIds.has(a.id));
      const sortedNew = [...newAlerts].sort((a, b) =>
        b.detectedAt.localeCompare(a.detectedAt),
      );
      const PREVIEW_CAP = 3;
      const previewed = sortedNew.slice(0, PREVIEW_CAP);
      const overflow =
        sortedNew.length -
        previewed.length +
        Math.max(0, affecting.length - sortedNew.length);

      return (
        <section className="mb-section">
          <SectionHeader
            title="Alerts to act on today"
            meta={`${newSinceLastVisit.length} new since last visit`}
            action={
              <Link
                to="/alerts"
                className="text-xs text-ink-500 hover:text-ink-900 inline-flex items-center gap-1"
              >
                All alerts <ChevronRight className="w-3 h-3" aria-hidden />
              </Link>
            }
          />
          <div className="bg-surface border border-line rounded-md overflow-hidden">
            <ul className="divide-y divide-line" role="list">
              {previewed.map((a) => (
                <CompactAlertRow
                  key={a.id}
                  announcement={a}
                  onClick={() => navigate(`/alerts/${a.id}`)}
                />
              ))}
            </ul>
            {overflow > 0 && (
              <Link
                to="/alerts"
                className="block w-full px-region py-2 text-xs text-ink-500 hover:text-ink-900 hover:bg-sunken/40 border-t border-line text-center"
              >
                {overflow} more {overflow === 1 ? "alert" : "alerts"} on /alerts →
              </Link>
            )}
          </div>
        </section>
      );
    }

    return (
      <Link
        to="/alerts"
        className="block bg-surface border border-line rounded-md px-4 py-2.5 flex items-center gap-3 mb-section hover:border-line-strong transition-colors"
        aria-label="State alerts"
      >
        <span
          className="w-2 h-2 rounded-full shrink-0 bg-info-solid"
          aria-hidden
        />
        <Megaphone className="w-3.5 h-3.5 shrink-0 text-ink-500" aria-hidden />
        <span className="flex-1 text-sm text-ink-700">
          <span className="font-medium text-ink-900 tabular-nums">
            {affecting.length}
          </span>{" "}
          {affecting.length === 1 ? "alert" : "alerts"} affecting your clients
          <span className="text-ink-500"> · all under SLA</span>
        </span>
        <span className="text-2xs text-ink-500 inline-flex items-center gap-0.5 shrink-0">
          Open <ChevronRight className="w-3 h-3" aria-hidden />
        </span>
      </Link>
    );
  }

  // Escalated present — sort escalated by impact (deadline-shifting,
  // then most clients) so the most urgent card is first.
  const sortedEscalated = [...escalated].sort((a, b) => {
    const aShift = a.newDeadline ? 1 : 0;
    const bShift = b.newDeadline ? 1 : 0;
    if (aShift !== bShift) return bShift - aShift;
    if (a.affectedClientIds.length !== b.affectedClientIds.length) {
      return b.affectedClientIds.length - a.affectedClientIds.length;
    }
    return b.detectedAt.localeCompare(a.detectedAt);
  });

  // Cap at 3 — Today's purpose is "act on the most urgent now," not browse
  // every escalation. Anything past 3 lives on /alerts.
  const PREVIEW_CAP = 3;
  const previewed = sortedEscalated.slice(0, PREVIEW_CAP);
  const overflow =
    escalated.length - previewed.length + Math.max(0, routineCount);

  // Freshness chip — appended to the SLA meta when any alerts have
  // arrived since the user's last visit. Replaces the old standalone
  // <WhatChangedBanner> that used to sit above this section.
  const slaLabel =
    escalated.length === 1
      ? "1 past 72h SLA"
      : `${escalated.length} past 72h SLA`;
  const meta =
    newSinceLastVisit.length > 0
      ? `${slaLabel} · ${newSinceLastVisit.length} new since last visit`
      : slaLabel;

  return (
    <section className="mb-section">
      <SectionHeader
        title="Alerts to act on today"
        meta={meta}
        action={
          <Link
            to="/alerts"
            className="text-xs text-ink-500 hover:text-ink-900 inline-flex items-center gap-1"
          >
            All alerts <ChevronRight className="w-3 h-3" aria-hidden />
          </Link>
        }
      />
      <div className="bg-surface border border-line rounded-md overflow-hidden">
        <ul className="divide-y divide-line" role="list">
          {previewed.map((a) => (
            <CompactAlertRow
              key={a.id}
              announcement={a}
              onClick={() => navigate(`/alerts/${a.id}`)}
            />
          ))}
        </ul>
        {overflow > 0 && (
          <Link
            to="/alerts"
            className="block w-full px-region py-2 text-xs text-ink-500 hover:text-ink-900 hover:bg-sunken/40 border-t border-line text-center"
          >
            {overflow} more {overflow === 1 ? "alert" : "alerts"} on /alerts →
          </Link>
        )}
      </div>
    </section>
  );
}

// CompactAlertRow — one-line summary of a single state alert. Strips
// down the StateAlertCard's full presentation (title + body + affected
// client list + nexus pill + source URL) to just the essentials Sarah
// needs to decide whether to act NOW: state, summary headline, affected
// count, recency, and a deadline-shift pill if applicable. Click lands
// on /alerts/:id where the full detail + actions live.
function CompactAlertRow({
  announcement,
  onClick,
}: {
  announcement: Announcement;
  onClick: () => void;
}) {
  const hours = hoursSince(announcement.detectedAt);
  const recency =
    hours < 1
      ? "just now"
      : hours < 24
        ? `${hours}h ago`
        : `${Math.floor(hours / 24)}d ago`;
  const affectedCount = announcement.affectedClientIds.length;
  // Use the title as the one-line headline (it's the distilled "Economic
  // nexus threshold lowered to $300,000" form). Summary is a longer body
  // paragraph — that lives on /alerts/:id, not here.
  const headline = announcement.title;
  return (
    <li>
      <button
        type="button"
        onClick={onClick}
        className="w-full text-left px-region py-2.5 flex items-center gap-3 hover:bg-sunken/40 transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-indigo/40"
      >
        <span className="inline-flex items-center justify-center min-w-[28px] h-5 px-1.5 rounded text-2xs font-semibold bg-sunken text-ink-700 shrink-0 tabular-nums">
          {announcement.stateCode}
        </span>
        <span className="flex-1 min-w-0 truncate text-sm text-ink-900">
          {headline}
        </span>
        {announcement.newDeadline && (
          <span className="text-2xs px-1.5 py-0.5 rounded bg-warn-bg text-warn-ink shrink-0 hidden sm:inline-block">
            moves deadline
          </span>
        )}
        <span className="text-xs text-ink-500 shrink-0 tabular-nums">
          {affectedCount} {affectedCount === 1 ? "client" : "clients"} ·{" "}
          {recency}
        </span>
        <ChevronRight
          className="w-3.5 h-3.5 text-ink-400 shrink-0"
          aria-hidden
        />
      </button>
    </li>
  );
}

function focusAdjacentRow(direction: 1 | -1) {
  const rows = Array.from(
    document.querySelectorAll<HTMLElement>("[data-deadline-row]"),
  );
  if (rows.length === 0) return;
  const active = document.activeElement as HTMLElement | null;
  const currentIndex = rows.findIndex((r) => r === active);
  const nextIndex =
    currentIndex === -1
      ? direction > 0
        ? 0
        : rows.length - 1
      : Math.max(0, Math.min(rows.length - 1, currentIndex + direction));
  rows[nextIndex]?.focus();
  rows[nextIndex]?.scrollIntoView({ block: "nearest", behavior: "smooth" });
}

function EmptyState({
  title,
  actions,
}: {
  title: string;
  actions: React.ReactNode;
}) {
  return (
    <div className="bg-surface border border-line rounded-md px-6 py-16 text-center">
      <p className="text-sm text-ink-700 font-medium">{title}</p>
      <div className="mt-4 flex items-center justify-center gap-2">
        {actions}
      </div>
    </div>
  );
}

function EmptyStateButton({
  to,
  primary,
  children,
}: {
  to: string;
  primary?: boolean;
  children: React.ReactNode;
}) {
  const cls = primary
    ? "text-sm px-3 py-1.5 rounded-md bg-indigo text-white hover:bg-indigo-hover"
    : "text-sm px-3 py-1.5 rounded-md border border-line text-ink-700 hover:bg-sunken";
  return (
    <a href={to} className={cls}>
      {children}
    </a>
  );
}
