import { useEffect, useMemo, useState } from "react";
import { useShortcuts } from "../hooks/useKeyboard";
import { useClients } from "../hooks/useClients";
import { useTriageDeadlines } from "../hooks/useDeadlines";
import { useDetectAnnouncements } from "../hooks/useAnnouncements";
import { useRealtimeAnnouncements } from "../hooks/useRealtimeAnnouncements";
import { ShortcutsModal } from "../components/ShortcutsModal";
import { DashboardSkeleton } from "../components/skeletons/DashboardSkeleton";
import { ErrorState } from "../components/ErrorState";
import {
  TODAY,
  toIso,
  hoursSince,
  escalationTier,
} from "../data/dateHelpers";
import { useDashboardPreferences } from "../data/preferences";
import { AnnouncementBanner } from "../components/AnnouncementBanner";
import { ChaseBanner } from "../components/ChaseBanner";
import { BlockingAlertsDialog } from "../components/BlockingAlertsDialog";
import { OnboardingLayer2Widget } from "../components/OnboardingLayer2Widget";
import { WelcomeTour } from "../components/WelcomeTour";
import { CapacityStrip } from "../components/CapacityStrip";
import { ActionQueue } from "../components/ActionQueue";
import { JustHappenedStrip } from "../components/JustHappenedStrip";
import { useLocation } from "react-router-dom";
import type { Announcement } from "../types";

/**
 * Dashboard — the morning glance.
 *
 * Three sections, top-to-bottom:
 *   1. Just happened — overnight diff strip (Mode A confirms, Mode C issues, replies)
 *   2. State alerts — every undismissed alert with inline state-health pill
 *   3. Action queue — verb-grouped per-client cards (chase, confirm, etc.)
 *
 * Quiet clients banner + Capacity strip render below when relevant.
 *
 * Per DESIGN.md, Today is an audit + batch surface, not a daily destination.
 * Header is date only. Mode F Health is now an inline pill (StateHealthPill)
 * embedded in the State alerts header — no separate card. Operational summary
 * and AI-usage chip live in Settings, not on Today.
 */
export function Dashboard() {
  const clientsQuery = useClients();
  const triageQuery = useTriageDeadlines();
  const announcementsQuery = useRealtimeAnnouncements();
  const detectMutation = useDetectAnnouncements();
  const location = useLocation();
  // /legacy/dashboard renders the pre-v0.7-amendment view: deadline list only,
  // no ActionQueue, no Mode F Health. Lets us A/B compare during transition.
  const isLegacy = location.pathname.startsWith("/legacy");

  // One-shot: run the detector on mount (simulates 24h SLA scrape)
  useEffect(() => {
    detectMutation.mutate();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const { prefs, update } = useDashboardPreferences();

  const [shortcutsOpen, setShortcutsOpen] = useState(false);

  useShortcuts([
    { key: "j", description: "Next row", handler: () => focusAdjacentRow(1) },
    { key: "k", description: "Previous row", handler: () => focusAdjacentRow(-1) },
    {
      key: "?",
      shift: true,
      description: "Show shortcuts",
      handler: () => setShortcutsOpen(true),
    },
  ]);

  const clients = clientsQuery.data?.items ?? [];
  const announcements = announcementsQuery.data ?? [];

  // Two surfaces work together (per Yuqi's "[State notification + suggested
  // actions = THE surface]" — the alert is the news; the queue carries the
  // derived verbs):
  //   • AnnouncementBanner ("State alerts") — receives EVERY undismissed
  //     alert. Renders actionable ones as full rows and folds news-only
  //     alerts into a "N news items" chip. This is the single canonical
  //     surface for the alerts themselves.
  //   • ActionQueue — receives state-alert TodoItems generated by Mode F
  //     (separately persisted on the BE). Surfaces the *actions* a CPA
  //     should take in response ("Review draft for 6 clients", etc.).
  //   The previous one-surface approach (PR #44 — alerts moved into queue,
  //   banner was news-only) failed when Mode F hadn't generated a
  //   corresponding TodoItem yet: alerts vanished from both surfaces and
  //   the user only saw "5 active alerts" in the StateMonitoringHealth
  //   strip with no way to act on them. Belt-and-suspenders: the banner
  //   always shows the alerts; the queue is a derived view, not the only
  //   path.
  const activeBanners = announcements.filter((a) => !a.dismissed);
  // firmRelevantAlerts (alerts hitting at least one client) still drives
  // the >72h blocking dialog — that escalation only makes sense when a
  // client cares about the alert.
  const firmRelevantAlerts = activeBanners.filter(
    (a) => a.affectedClientIds.length > 0,
  );

  const alertsByTier = useMemo(() => {
    const out = {
      fresh: [] as Announcement[],
      reminder: [] as Announcement[],
      escalated: [] as Announcement[],
      blocking: [] as Announcement[],
    };
    for (const a of firmRelevantAlerts) {
      out[escalationTier(hoursSince(a.detectedAt))].push(a);
    }
    return out;
  }, [firmRelevantAlerts]);

  const alertsSnoozedToday = prefs.alerts_snoozed_until === toIso(TODAY);
  const showBlockingDialog =
    alertsByTier.blocking.length > 0 && !alertsSnoozedToday;
  const [blockingDismissed, setBlockingDismissed] = useState(false);

  const todayLabel = useMemo(
    () =>
      TODAY.toLocaleDateString("en-US", {
        weekday: "long",
        month: "long",
        day: "numeric",
      }),
    [],
  );

  const hasNoClients = clients.length === 0;

  const isLoading = clientsQuery.isLoading || triageQuery.isLoading;
  const loadError =
    clientsQuery.error || triageQuery.error || announcementsQuery.error;

  if (isLoading) return <DashboardSkeleton />;

  if (loadError) {
    return (
      <div className="max-w-[840px] mx-auto px-page-x py-page-y">
        <ErrorState
          title="Couldn't load your dashboard."
          message={loadError instanceof Error ? loadError.message : undefined}
          onRetry={() => {
            clientsQuery.refetch();
            triageQuery.refetch();
            announcementsQuery.refetch();
          }}
        />
      </div>
    );
  }

  if (hasNoClients) {
    return (
      <div className="max-w-[840px] mx-auto px-page-x py-page-y space-y-card">
        <EmptyState
          title="Let's get your clients in."
          actions={
            <>
              <EmptyStateButton to="/import" primary>
                Import CSV
              </EmptyStateButton>
              <EmptyStateButton to="/clients">Add 5 manually</EmptyStateButton>
              <EmptyStateButton to="/import?demo=1">
                Try demo data
              </EmptyStateButton>
            </>
          }
        />
      </div>
    );
  }

  return (
    <div className="max-w-[840px] mx-auto px-page-x py-page-y space-y-section">
      {/* Header — date only. Per DESIGN.md: no greeting, no firm name,
          no AI-usage chip, no operational summary. The sidebar tells you
          where you are; the date is the only chrome that changes. */}
      <header>
        <h1 className="text-2xl font-semibold text-ink-900">Today</h1>
        <p className="text-sm text-ink-500 mt-0.5">{todayLabel}</p>
      </header>

      {/* First-run welcome — inline banner, click to expand. Self-gated
          to fade after first session. */}
      <WelcomeTour />

      {/* §1: Just happened — overnight diff strip. Auto-hides at 0/0/0. */}
      <JustHappenedStrip />

      {/* §2: State alerts — banner always renders so a fresh firm sees
          the "All clear" stripe (monitoring 50 states). The State-health
          pill rides inline in the section header (replaces the previous
          ModeFHealth card on Today, per DESIGN.md). */}
      <AnnouncementBanner announcements={activeBanners} />

      {/* §3: Action queue — verb-grouped per-client cards (PRD §4.8). */}
      {!isLegacy && <ActionQueue />}

      {/* Quiet clients — temporary placement; folds into the Action
          queue card stack in a follow-up PR. Self-vanishes at zero. */}
      <ChaseBanner />

      {/* Capacity — ≥3-staff firms only (gate inside the component). */}
      <CapacityStrip />

      {/* Onboarding nudges — self-gates after wiring is done. */}
      <OnboardingLayer2Widget />

      {/* Blocking-alerts overlay — fires only at >72h escalation. Stays as
          a modal because the spec demands a forced ack at that tier. */}
      {showBlockingDialog && !blockingDismissed && (
        <BlockingAlertsDialog
          alerts={alertsByTier.blocking}
          onSnooze={(reason) => {
            update({ alerts_snoozed_until: toIso(TODAY) });
            if (reason) {
              console.info("[alerts] snooze logged", {
                date: toIso(TODAY),
                reason,
              });
            }
            setBlockingDismissed(true);
          }}
          onClose={() => setBlockingDismissed(true)}
        />
      )}

      <ShortcutsModal
        open={shortcutsOpen}
        onClose={() => setShortcutsOpen(false)}
        shortcuts={[
          { keys: ["j"], label: "Next deadline row" },
          { keys: ["k"], label: "Previous deadline row" },
          { keys: ["Enter"], label: "Open focused row's actions" },
          { keys: ["c"], label: "Mark focused row complete" },
          { keys: ["/"], label: "Focus filter" },
          { keys: ["⌘", "k"], label: "Open search" },
          { keys: ["?"], label: "Show this help" },
          { keys: ["Esc"], label: "Close dialog" },
        ]}
      />
    </div>
  );
}

function focusAdjacentRow(direction: 1 | -1) {
  const rows = Array.from(
    document.querySelectorAll<HTMLElement>("[data-deadline-row]"),
  );
  if (rows.length === 0) return;
  const active = document.activeElement as HTMLElement | null;
  const currentIndex = rows.findIndex((r) => r === active);
  const nextIndex =
    currentIndex === -1
      ? direction > 0
        ? 0
        : rows.length - 1
      : Math.max(0, Math.min(rows.length - 1, currentIndex + direction));
  rows[nextIndex]?.focus();
  rows[nextIndex]?.scrollIntoView({ block: "nearest", behavior: "smooth" });
}

function EmptyState({
  title,
  actions,
}: {
  title: string;
  actions: React.ReactNode;
}) {
  return (
    <div className="bg-surface border border-line rounded-md px-6 py-16 text-center">
      <p className="text-sm text-ink-700 font-medium">{title}</p>
      <div className="mt-4 flex items-center justify-center gap-2">
        {actions}
      </div>
    </div>
  );
}

function EmptyStateButton({
  to,
  primary,
  children,
}: {
  to: string;
  primary?: boolean;
  children: React.ReactNode;
}) {
  // Two affordances per DESIGN.md: solid primary or text-only link.
  const cls = primary
    ? "text-sm px-3 py-1.5 rounded-md bg-accent text-canvas hover:bg-accent-hover"
    : "text-sm text-ink-700 hover:text-ink-900 underline-offset-4 hover:underline";
  return (
    <a href={to} className={cls}>
      {children}
    </a>
  );
}
