import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { Check, MoreHorizontal } from "lucide-react";
import type { Client, Deadline, DeadlineStatus } from "../types";
import { countdownLabel, daysBetween, parseDate, TODAY } from "../data/dateHelpers";
import { actions } from "../data/store";
import { bundleById } from "../data/bundles";
import { QuickActionModal } from "./QuickActionModal";

type UrgencyTone = "danger" | "warn" | "neutral";
type DotShape = "filled" | "half" | "empty";

function urgency(d: Deadline): UrgencyTone {
  const days = daysBetween(TODAY, parseDate(d.officialDueDate));
  if (days <= 0) return "danger";
  if (days <= 3 || d.status === "in_progress") return "warn";
  return "neutral";
}

function dotShape(d: Deadline): DotShape {
  const days = daysBetween(TODAY, parseDate(d.officialDueDate));
  if (days <= 0 || d.status === "overdue") return "filled";
  if (d.status === "in_progress") return "half";
  return "empty";
}

const toneStroke: Record<UrgencyTone, string> = {
  danger: "text-danger-solid",
  warn: "text-warn-solid",
  neutral: "text-ink-300",
};

function Dot({ tone, shape }: { tone: UrgencyTone; shape: DotShape }) {
  const color = toneStroke[tone];
  if (shape === "filled") {
    return (
      <svg viewBox="0 0 8 8" className={`w-2 h-2 ${color}`} aria-hidden>
        <circle cx="4" cy="4" r="4" fill="currentColor" />
      </svg>
    );
  }
  if (shape === "half") {
    return (
      <svg viewBox="0 0 8 8" className={`w-2 h-2 ${color}`} aria-hidden>
        <circle cx="4" cy="4" r="3.5" fill="none" stroke="currentColor" strokeWidth="1" />
        <path d="M4 0.5 A 3.5 3.5 0 0 1 4 7.5 Z" fill="currentColor" />
      </svg>
    );
  }
  return (
    <svg viewBox="0 0 8 8" className={`w-2 h-2 ${color}`} aria-hidden>
      <circle cx="4" cy="4" r="3" fill="none" stroke="currentColor" strokeWidth="1.2" />
    </svg>
  );
}

function statusLabel(s: DeadlineStatus): string | null {
  const map: Record<DeadlineStatus, string | null> = {
    not_started: null,
    in_progress: "In progress",
    completed: "Completed",
    deferred: "Deferred",
    filed_extension: "Extension filed",
    overdue: "Overdue",
  };
  return map[s];
}

interface Props {
  deadline: Deadline;
  client: Client;
  suppressClientName?: boolean;
  inOverdueSection?: boolean;
}

export function DeadlineRow({
  deadline,
  client,
  suppressClientName = false,
  inOverdueSection = false,
}: Props) {
  const [modalOpen, setModalOpen] = useState(false);
  const navigate = useNavigate();
  const taskHref = `/clients/${client.id}/tasks/t-${deadline.id}`;
  const tone = urgency(deadline);
  const shape = dotShape(deadline);
  const isOverdue = deadline.status === "overdue";
  const showStatus =
    statusLabel(deadline.status) && !(inOverdueSection && isOverdue);
  const jurisdictionTag =
    deadline.jurisdiction === "federal" ? "federal" : deadline.jurisdiction;
  const bundle = deadline.bundleId ? bundleById(deadline.bundleId) : null;
  const sourceLabel = bundle
    ? `Generated by: ${bundle.name} (${jurisdictionTag})`
    : `Manually added · ${jurisdictionTag}`;

  const onComplete = (e: React.MouseEvent) => {
    e.preventDefault();
    e.stopPropagation();
    actions.setDeadlineStatus(deadline.id, "completed");
  };

  return (
    <>
      <div
        title={sourceLabel}
        data-deadline-row
        data-deadline-id={deadline.id}
        tabIndex={0}
        onKeyDown={(e) => {
          if (e.key === "Enter") {
            e.preventDefault();
            navigate(taskHref);
          } else if (e.key === " ") {
            e.preventDefault();
            setModalOpen(true);
          } else if (e.key === "c" && !e.metaKey && !e.ctrlKey) {
            e.preventDefault();
            actions.setDeadlineStatus(deadline.id, "completed");
          }
        }}
        className={[
          "group flex items-center gap-3 px-4 h-11 outline-none",
          "border-b border-line last:border-b-0",
          isOverdue ? "bg-danger-bg hover:bg-danger-bg/70" : "hover:bg-sunken",
          "focus:bg-sunken focus-within:bg-sunken",
          "focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-indigo",
          suppressClientName && "pl-8",
        ]
          .filter(Boolean)
          .join(" ")}
      >
        <span className="w-2 h-2 shrink-0 flex items-center justify-center">
          <Dot tone={tone} shape={shape} />
        </span>

        <span
          className={`text-xs font-medium tabular-nums w-16 shrink-0 ${
            tone === "danger" ? "text-danger-ink" : "text-ink-500"
          }`}
        >
          {countdownLabel(deadline.officialDueDate)}
        </span>

        <div className="w-48 shrink-0 min-w-0">
          {suppressClientName ? (
            <span className="text-xs text-ink-300" aria-hidden>
              ↪
            </span>
          ) : (
            <Link
              to={`/clients/${client.id}`}
              className="text-sm font-medium text-ink-900 hover:underline truncate block"
            >
              {client.name}
            </Link>
          )}
        </div>

        <Link
          to={taskHref}
          className="text-sm text-ink-700 flex-1 truncate min-w-0 hover:text-ink-900 hover:underline"
          title="Open task"
        >
          {deadline.form}
        </Link>

        <JurisdictionChip
          code={deadline.jurisdiction}
          isPrimary={deadline.jurisdiction === client.primaryState}
        />

        {showStatus && (
          <span className="text-xs text-ink-500 w-24 truncate shrink-0">
            {statusLabel(deadline.status)}
          </span>
        )}

        <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 group-focus-within:opacity-100 transition-opacity shrink-0">
          <button
            onClick={onComplete}
            aria-label="Mark complete"
            title="Mark complete (c)"
            className="text-xs p-1.5 rounded bg-ok-bg text-ok-ink hover:bg-ok-border/40"
          >
            <Check className="w-3.5 h-3.5" aria-hidden />
          </button>
          <button
            onClick={() => setModalOpen(true)}
            aria-label="More actions"
            className="text-xs p-1.5 rounded hover:bg-sunken text-ink-500"
          >
            <MoreHorizontal className="w-3.5 h-3.5" aria-hidden />
          </button>
        </div>
      </div>

      <QuickActionModal
        open={modalOpen}
        deadline={deadline}
        client={client}
        onClose={() => setModalOpen(false)}
      />
    </>
  );
}

function JurisdictionChip({
  code,
  isPrimary,
}: {
  code: string;
  isPrimary: boolean;
}) {
  const isFederal = code === "federal";
  const base =
    "text-2xs uppercase tracking-wide px-1.5 py-0.5 rounded font-medium shrink-0";
  if (isFederal)
    return <span className={`${base} bg-sunken text-ink-700`}>FED</span>;
  if (isPrimary)
    return (
      <span className={`${base} bg-ink-900 text-canvas`}>{code}</span>
    );
  return (
    <span className={`${base} border border-line-strong text-ink-500`}>
      {code}
    </span>
  );
}
