import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import type { Client, Deadline } from "../types";
import { actions } from "../data/store";
import { bundleById } from "../data/bundles";
import { formatLongDate, toIso, addDays, TODAY } from "../data/dateHelpers";
import { useModalDialog } from "../hooks/useModalDialog";
import { useAddNote } from "../hooks/useClients";
import { env } from "../config";

type Mode = "choose" | "defer" | "note";

export function QuickActionModal({
  open,
  deadline,
  client,
  onClose,
}: {
  open: boolean;
  deadline: Deadline | null;
  client: Client | null;
  onClose: () => void;
}) {
  const [mode, setMode] = useState<Mode>("choose");
  const [deferDate, setDeferDate] = useState<string>(
    toIso(addDays(TODAY, 14))
  );
  const [note, setNote] = useState<string>("");
  const addNoteMutation = useAddNote();

  useEffect(() => {
    if (open) {
      setMode("choose");
      setDeferDate(toIso(addDays(TODAY, 14)));
      setNote("");
    }
  }, [open]);

  const dialogRef = useModalDialog(open, onClose);

  if (!open || !deadline || !client) return null;

  const jurisdictionTag =
    deadline.jurisdiction === "federal" ? "federal" : deadline.jurisdiction;
  const bundle = deadline.bundleId ? bundleById(deadline.bundleId) : null;
  const sourceLabel = bundle
    ? `Generated by: ${bundle.name} (${jurisdictionTag})`
    : `Manually added · ${jurisdictionTag}`;

  const close = () => onClose();

  const onComplete = () => {
    actions.setDeadlineStatus(deadline.id, "completed");
    close();
  };
  const onInProgress = () => {
    actions.setDeadlineStatus(deadline.id, "in_progress");
    close();
  };
  const onDeferSubmit = () => {
    actions.deferDeadline(deadline.id, deferDate);
    close();
  };
  const onFiledExtension = () => {
    actions.fileExtension(deadline.id);
    close();
  };
  const onNoteSubmit = () => {
    const body = note.trim();
    if (!body) return;
    if (env.useMockData) {
      actions.addNote(client.id, body, deadline.id);
    } else {
      addNoteMutation.mutate({
        clientId: client.id,
        body,
        relatedDeadlineId: deadline.id,
      });
    }
    close();
  };

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-ink-900/40 backdrop-blur-sm"
      onClick={close}
    >
      <div
        ref={dialogRef}
        tabIndex={-1}
        role="dialog"
        aria-modal="true"
        onClick={(e) => e.stopPropagation()}
        className="bg-surface rounded-lg shadow-xl border border-line w-full max-w-md mx-4 outline-none"
      >
        <div className="px-5 py-3 border-b border-line">
          <div className="text-xs uppercase tracking-wide text-ink-500">
            {client.name}
          </div>
          <div className="text-sm font-semibold text-ink-900">
            {deadline.form} ·{" "}
            <span className="font-normal text-ink-700">
              {formatLongDate(deadline.officialDueDate)}
            </span>
          </div>
          <div className="text-2xs text-ink-500 mt-0.5">{sourceLabel}</div>
        </div>

        {mode === "choose" && (
          <ul className="py-1">
            <ActionRow
              label="Mark complete"
              hint="Closes this deadline and logs activity"
              onClick={onComplete}
            />
            <ActionRow
              label="Mark in progress"
              hint="Signals you've started — shows a half-filled dot"
              onClick={onInProgress}
            />
            <ActionRow
              label="Defer to a later date…"
              hint="Pushes the due date; status becomes Deferred"
              onClick={() => setMode("defer")}
            />
            <ActionRow
              label="Filed extension"
              hint="Creates a new extension deadline (+6 months by default)"
              onClick={onFiledExtension}
            />
            <ActionRow
              label="Add note"
              hint="Attach a note to this deadline"
              onClick={() => setMode("note")}
            />
            <li className="px-5 py-2 border-t border-line mt-1">
              <Link
                to={`/clients/${client.id}`}
                onClick={close}
                className="text-sm text-ink-500 hover:text-ink-900"
              >
                View client detail →
              </Link>
            </li>
          </ul>
        )}

        {mode === "defer" && (
          <div className="px-5 py-4 space-y-3">
            <label className="block text-xs font-medium text-ink-700">
              New due date
              <input
                type="date"
                value={deferDate}
                onChange={(e) => setDeferDate(e.target.value)}
                className="mt-1 w-full px-2.5 py-1.5 rounded border border-line focus:outline-none focus:ring-2 focus:ring-indigo text-sm"
              />
            </label>
            <p className="text-xs text-ink-500">
              Defers only this deadline. Official IRS date stays archived in
              the activity log.
            </p>
            <div className="flex justify-end gap-2">
              <button
                onClick={() => setMode("choose")}
                className="text-sm px-3 py-1.5 rounded border border-line hover:bg-canvas"
              >
                ← Back
              </button>
              <button
                onClick={onDeferSubmit}
                className="text-sm px-3 py-1.5 rounded bg-indigo text-white hover:bg-indigo-hover"
              >
                Defer
              </button>
            </div>
          </div>
        )}

        {mode === "note" && (
          <div className="px-5 py-4 space-y-3">
            <label className="block text-xs font-medium text-ink-700">
              Note body
              <textarea
                autoFocus
                value={note}
                onChange={(e) => setNote(e.target.value)}
                rows={4}
                placeholder="e.g. Waiting on K-1 from Acme 1065"
                className="mt-1 w-full px-2.5 py-1.5 rounded border border-line focus:outline-none focus:ring-2 focus:ring-indigo text-sm resize-none"
              />
            </label>
            <div className="flex justify-end gap-2">
              <button
                onClick={() => setMode("choose")}
                className="text-sm px-3 py-1.5 rounded border border-line hover:bg-canvas"
              >
                ← Back
              </button>
              <button
                onClick={onNoteSubmit}
                disabled={!note.trim()}
                className="text-sm px-3 py-1.5 rounded bg-indigo text-white hover:bg-indigo-hover disabled:opacity-40"
              >
                Save note
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

function ActionRow({
  label,
  hint,
  onClick,
}: {
  label: string;
  hint: string;
  onClick: () => void;
}) {
  return (
    <li>
      <button
        onClick={onClick}
        className="w-full text-left px-5 py-2.5 hover:bg-canvas"
      >
        <div className="text-sm text-ink-900 font-medium">{label}</div>
        <div className="text-xs text-ink-500">{hint}</div>
      </button>
    </li>
  );
}
